title: Ben Edmonds 
logo: "images/Headshot .jpg" 
description: > 
  Computer Science Student at Seattle Pacific University
  <br><br>
  Experience involving data structures, object-oriented programing, graphical user interfaces, algorithms and efficiency
  <br><br>
  C++, C, C#, HTMl/CSS, Javascript
  <br>
  Familiar working in Windows, Linux, Visual Studios, VS Code, QT Development
  <br><br>
  Email: edmondsb@spu.edu
  <br><br>
  <a href="https://www.linkedin.com/in/ben-edmonds/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

