title: Ben Edmonds 
logo: "images/Headshot .jpg" 
description: > 
  B.S. Computer Science
  <br>
  Seattle Pacific University
  <br>
  Graduation June 2021
  <br><br>
  Experience involving data structures, object-oriented programing, graphical user interfaces, algorithms and efficiency
  <br><br>
  C++, C, C#, Javascript
  <br>
  Windows, Linux, Visual Studios/VS Code
  <br>
  <a href="https://www.youracclaim.com/badges/b9d333e5-539c-4008-997a-6b355d5f21c0?source=linked_in_profile/">Microsoft Certified: Azure Fundamentals</a>
  <br><br>
  Email: edmondsb@spu.edu
  <br><br>
  <a href="https://www.linkedin.com/in/ben-edmonds/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

